timeout 3
use_graphics_for osx,linux,windows
include themes/rEFInd-minimal/theme.conf
scanfor manual

menuentry "NixOS" {
    icon /EFI/refind/themes/rEFInd-minimal/icons/os_nixos.png
    loader /EFI/systemd/systemd-bootx64.efi
    graphics on
}

menuentry "Windows" {
    icon /EFI/refind/themes/rEFInd-minimal/icons/os_win.png
    loader \EFI\Microsoft\Boot\bootmgfw.efi
}