cursor #e6e1e3
cursor_text_color #c9c5c7

foreground            #e6e1e3
background            #141314
selection_foreground  #322f38
selection_background  #cac4cf
url_color             #cbc3d5

color0   #141314
color1   #f46e87
color2   #6ad582
color3   #ffdb72
color4   #beb5ca
color5   #5a5362
color6   #cbc3d5
color7   #d8d2df
color8   #84808a
color9   #ff9fb1
color10  #a5ffb9
color11  #ffe8a5
color12  #e0d9ea
color13  #f6efff
color14  #f9f5ff
color15  #fbf8ff
