general {
    lock_cmd = (pidof hyprlock || hyprlock -q) || niri msg action quit --skip-confirmation
    before_sleep_cmd = (pidof hyprlock || hyprlock -q) || niri msg action quit --skip-confirmation
    after_sleep_cmd = $HOME/scripts/hypridle/restore-kbd-brightness.sh
}

# If not locked, dim screen after 6 min
listener {
    timeout = 360   # 6 min
    on-timeout = pidof hyprlock || $HOME/scripts/hypridle/save-brightness-and-dim.sh
    on-resume  = $HOME/scripts/hypridle/restore-brightness.sh
}

# If not locked, lock and turn off screen after 7 min
listener {
    timeout = 420   # 7 min
    on-timeout = pidof hyprlock || (niri msg action power-off-monitors && hyprlock -q)
    on-resume  = $HOME/scripts/hypridle/restore-brightness.sh
}

# If locked, dim screen after 1 min
listener {
    timeout = 60    # 1 min
    on-timeout = pidof hyprlock && $HOME/scripts/hypridle/save-brightness-and-dim.sh
    on-resume  = $HOME/scripts/hypridle/restore-brightness.sh
}

# If locked, turn screen off after 2 min
listener {
    timeout = 120   # 2 min
    on-timeout = pidof hyprlock && niri msg action power-off-monitors
    on-resume  = $HOME/scripts/hypridle/restore-brightness.sh
}

# Keyboard dimming
listener {
    timeout = 20
    on-timeout = $HOME/scripts/hypridle/save-kbd-brightness-and-dim.sh
    on-resume  = $HOME/scripts/hypridle/restore-kbd-brightness.sh
}