# Generated by scripts/luks-tpm-autounlock.sh -- do not edit by hand.
# /etc/nixos is the source of truth; the update alias and autoupgrade service
# copy it over the dotfiles copy before every rebuild.
#
# TPM2 auto-unlock is OFF: the LUKS passphrase is entered at every boot.
{ ... }:

{
  # Kept regardless of TPM state. The systemd initrd runs the password agent
  # that draws the Plymouth passphrase prompt; dropping it here would silently
  # send this host back to the scripted initrd.
  boot.initrd.systemd.enable = true;
}
