hideui all
icons_dir themes/rEFInd-minimal/icons
banner themes/rEFInd-minimal/background.png
banner_scale fillscreen
selection_big   themes/rEFInd-minimal/selection_big.png
selection_small themes/rEFInd-minimal/selection_small.png
showtools shutdown, reboot