#!/usr/bin/env bash
set -euo pipefail
clear

if [ "$(id -u)" -eq 0 ]; then
  gum log --level error "Don't run as root, sudo is invoked as needed."
  exit 1
fi

REPO="https://github.com/taylorstools/dotfiles"
DOTFILES_DIR="$HOME/.dotfiles"
INSTALLER_DIR="/etc/nixos-installer"
HOST=$(hostname)
HOST_DIR="$DOTFILES_DIR/nixos/hosts/$HOST"

gum style \
  --border double --border-foreground 39 \
  --padding "1 4" --margin "1 0" \
  --bold "NixOS Post-Install Script"

gum log --level info "Detected host: $HOST"

if [ ! -d "$INSTALLER_DIR" ]; then
  gum log --level warn "No $INSTALLER_DIR, was this booted from install.sh?"
  gum confirm "Continue anyway?" || exit 1
fi

# Prompt to change default password
if [ -f "$INSTALLER_DIR/configuration.nix" ] \
   && grep -q 'initialPassword = "password"' "$INSTALLER_DIR/configuration.nix"; then
  gum log --level warn "Default 'password' password may still be active."
  gum confirm "Set a real password now?" && passwd
fi

# rEFInd prompt (taylorpc only)
REFIND_ANSWER="n"
if [[ "$HOST" == "taylorpc" ]]; then
  echo
  gum confirm "Configure rEFInd?" && REFIND_ANSWER="y" || REFIND_ANSWER="n"
fi

# Clone or update dotfiles
echo
gum log --level info "Cloning dotfiles..."
if [ ! -d "$DOTFILES_DIR" ]; then
  git clone "$REPO" "$DOTFILES_DIR"
else
  gum log --level warn "Dotfiles already exist, pulling latest..."
  git -C "$DOTFILES_DIR" pull --ff-only
fi

# Sanity check: host directory must exist in dotfiles
if [ ! -d "$HOST_DIR" ]; then
  gum log --level error "Host directory not found: $HOST_DIR"
  gum log --level error "The running hostname '$HOST' has no matching dotfiles host config."
  exit 1
fi

# Generate hardware-configuration.nix
gum log --level info "Generating hardware-configuration.nix..."
TMP_HW=$(mktemp -d)
sudo nixos-generate-config --no-filesystems --dir "$TMP_HW"
sudo cp -f "$TMP_HW/hardware-configuration.nix" "$HOST_DIR/hardware-configuration.nix"
sudo chown "$USER:" "$HOST_DIR/hardware-configuration.nix"
sudo rm -rf "$TMP_HW"
git -C "$DOTFILES_DIR" add --intent-to-add -f \
  "nixos/hosts/$HOST/hardware-configuration.nix"

# Bring forward the ZFS hostId
if [ -f "$INSTALLER_DIR/hostid" ]; then
  HOSTID=$(cat "$INSTALLER_DIR/hostid")
  cat > "$HOST_DIR/hostid.nix" <<EOF
# Generated by postinstall.sh; matches the hostId used when the ZFS pool was
# created. The pool will refuse to import on a system with a different hostId.
{ networking.hostId = "$HOSTID"; }
EOF
  git -C "$DOTFILES_DIR" add --intent-to-add -f "nixos/hosts/$HOST/hostid.nix"
  gum log --level info "Wrote hostId $HOSTID → hosts/$HOST/hostid.nix"

  if ! grep -q "./hostid.nix" "$HOST_DIR/configuration.nix"; then
    gum log --level error "hosts/$HOST/configuration.nix does not import ./hostid.nix"
    gum log --level error "Add ./hostid.nix to its imports = [...] list, commit, re-run."
    exit 1
  fi
fi

# Carry forward disko.nix if the host doesn't have one yet
if [ -f "$INSTALLER_DIR/disko.nix" ] && [ ! -f "$HOST_DIR/disko.nix" ]; then
  gum log --level info "Copying installer disko.nix → hosts/$HOST/disko.nix"
  cp "$INSTALLER_DIR/disko.nix" "$HOST_DIR/disko.nix"
  git -C "$DOTFILES_DIR" add --intent-to-add -f "nixos/hosts/$HOST/disko.nix"
  gum log --level warn "Make sure hosts/$HOST/configuration.nix imports disko's module and ./disko.nix"
fi

# Apply dotfiles
echo
gum log --level info "Applying dotfiles with chezmoi..."
chezmoi init --source "$DOTFILES_DIR" --apply "$REPO" --force

# LUKS TPM autounlock
if [ -x "$HOME/scripts/luks-tpm-autounlock.sh" ]; then
  "$HOME/scripts/luks-tpm-autounlock.sh" --hostname "$HOST" --norebuild
fi

# User directories
if [ -x "$HOME/scripts/update-user-dirs.sh" ]; then
  "$HOME/scripts/update-user-dirs.sh"
fi

# rEFInd
if [[ "$REFIND_ANSWER" == "y" ]] && [ -x "$HOME/scripts/rEFInd/nix_install-refind.sh" ]; then
  "$HOME/scripts/rEFInd/nix_install-refind.sh"
fi

# Update flake
gum style \
  --border double --border-foreground 39 \
  --padding "1 4" --margin "1 0" \
  --bold "Flake Update & Rebuild"

gum log --level info "Updating Nix flake..."
nix --extra-experimental-features "nix-command flakes" \
  flake update --flake "$DOTFILES_DIR/nixos"

# Apply system configuration
echo
gum log --level info "Applying system configuration..."
sudo nixos-rebuild boot --flake "$DOTFILES_DIR/nixos#$HOST"

# Done
echo
gum log --level info "POST-INSTALL SCRIPT COMPLETE."

if gum confirm "Reboot now?"; then
  [ -d "$HOME/rEFI2nd" ] && rm -rf "$HOME/rEFI2nd"
  sudo reboot
fi